---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-brahms-amd-sp
  labels:
    app: etl-brahms-amd-sp
spec:
  template:
    metadata:
      name: etl-brahms-amd-sp
      labels:
        app: etl-brahms-amd-sp
    spec:
      containers:
      - name: etl-brahms-amd-sp
        image: atzedevries/docker-nba-etl:V2.6-30-g365f14cb
        env:
        - name: "ES_DNS"
          value: "elasticsearch"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "AUTO_IMPORT"
          value: "TRUE"
        - name: "ENABLE_FILEBEAT"
          value: "TRUE"
        - name: "DEFAULT_SHARDS"
          value: "6"
        - name: "NUM_REPLICAS"
          value: "0"
        - name: "DISABLE_TRUNCATE"
          value: "FALSE"
        - name: "REPOS"
          value: "nba-brondata-brahms:prisma-test,nba-brondata-medialib:prisma-test"
        - name: "IMPORT_COMMAND"
          value: "./brahms-import specimens AMD_30-06-2016_at_15-06-11.CSV"
        imagePullPolicy: Always
      restartPolicy: Never
