---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-crs-multimedia
  labels:
    app: etl-crs-multimedia
spec:
  template:
    metadata:
      name: etl-crs-multimedia
      labels:
        app: etl-crs-multimedia
    spec:
      containers:
      - name: etl-crs-multimedia
        image: atzedevries/docker-nba-etl:V2.6-30-g365f14cb
        env:
        - name: "ES_DNS"
          value: "elasticsearch"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "AUTO_IMPORT"
          value: "TRUE"
        - name: "ENABLE_FILEBEAT"
          value: "TRUE"
        - name: "DEFAULT_SHARDS"
          value: "6"
        - name: "NUM_REPLICAS"
          value: "0"
        - name: "REPOS"
          value: "nba-brondata-crs:prisma-test,nba-brondata-medialib:prisma-test"
        - name: "IMPORT_COMMAND"
          value: "./crs-import multimedia"
        imagePullPolicy: Always
      restartPolicy: Never
