---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl
  labels:
    app: etl
spec:
  template:
    metadata:
      name: etl
      labels:
        app: etl
    spec:
      containers:
      - name: etl
        image: atzedevries/docker-nba-etl:V2.3-49-g1d52dfbe
        env:
        - name: "ES_DNS"
          value: "elasticsearch"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "AUTO_IMPORT"
          value: "TRUE"
        - name: "ENABLE_FILEBEAT"
          value: "TRUE"
        - name: "DEFAULT_SHARDS"
          value: "24"
        - name: "NUM_REPLICAS"
          value: "0"
        - name: "IMPORT_COMMAND"
          value: "./import-all single"
        imagePullPolicy: Always
        volumeMounts:
        - name: nba-etl
          mountPath: /payload/data
      restartPolicy: Never
      volumes:
      - name: nba-etl
        persistentVolumeClaim:
          claimName: nba-etl
      nodeSelector:
        disk: slim
