kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nba-etl
  annotations:
    volume.beta.kubernetes.io/storage-class: cinder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
