---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-enrich-specimens
  labels:
    app: etl-enrich-specimens
spec:
  template:
    metadata:
      name: etl-enrich-specimens
      labels:
        app: etl-enrich-specimens
    spec:
      containers:
      - name: etl-enrich-specimens
        image: atzedevries/docker-nba-etl:V2.3-33-ga5be08ea
        env:
        - name: "ES_DNS"
          value: "elasticsearch"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "AUTO_IMPORT"
          value: "TRUE"
        - name: "ENABLE_FILEBEAT"
          value: "TRUE"
        - name: "IMPORT_COMMAND"
          value: "./enrich-specimens"
        imagePullPolicy: Always
        volumeMounts:
        - name: nba-etl
          mountPath: /payload/data
      restartPolicy: Never
      volumes:
      - name: nba-etl
        persistentVolumeClaim:
          claimName: nba-etl
      nodeSelector:
        disk: fat
