---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-brahms-amd-mm
  labels:
    app: etl-brahms-amd-mm
spec:
  template:
    metadata:
      name: etl-brahms-amd-mm
      labels:
        app: etl-brahms-amd-mm
    spec:
      restartPolicy: Never
      containers:
      - name: etl-brahms-mm
        image: atzedevries/docker-nba-etl:V2.6-69-g9d0757e4a
        env:
        - name: "ES_DNS"
          value: "elasticsearch"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "AUTO_IMPORT"
          value: "TRUE"
        - name: "ENABLE_FILEBEAT"
          value: "FALSE"
        - name: "DEFAULT_SHARDS"
          value: "6"
        - name: "NUM_REPLICAS"
          value: "0"
        - name: "DISABLE_TRUNCATE"
          value: "TRUE"
        - name: "REPOS"
          value: "nba-brondata-brahms:2017-07,nba-brondata-medialib:2017-07"
        - name: "IMPORT_COMMAND"
          value: "./brahms-import multimedia AMD_13-07-2017_at_11-42-59-2.CSV"
        imagePullPolicy: Always
        volumeMounts:
        - name: nfs-pvc
          mountPath: "/payload/software/log"
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfslog
