---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etl
  labels:
    app: etl
spec:
  replicas: 1
  template:
    metadata:
      name: etl
      labels:
        app: etl
    spec:
      containers:
      - name: etl
        image: atzedevries/docker-nba-etl:V2.6-30-g365f14cb
        env:
        - name: "ES_DNS"
          value: "elasticsearch"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "FALSE"
          value: "TRUE"
        - name: "DISABLE_TRUNCATE"
          value: "TRUE"
        imagePullPolicy: Always
        volumeMounts:
        - name: nfs-pvc
          mountPath: "/payload/software/log"
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfslog

