---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etl
  labels:
    app: etl
spec:
  replicas: 1
  template:
    metadata:
      name: etl
      labels:
        app: etl
    spec:
      containers:
      - name: etl
        image: atzedevries/docker-nba-etl:V2.3-20-g461dab56
        env:
        - name: "ES_DNS"
          value: "elasticsearch"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "AUTO_IMPORT"
          value: "TRUE"
        imagePullPolicy: Always
        volumeMounts:
        - name: nba-etl
          mountPath: /payload/data
      volumes:
      - name: nba-etl
        persistentVolumeClaim:
          claimName: nba-etl
      nodeSelector:
        disk: slim
