apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  labels:
    component: elasticsearch
    role: data
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - port: 9300
    name: transport
  selector:
    component: elasticsearch
    role: data
