---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-enrich-specimens-mm
  labels:
    app: etl-enrich-specimens-mm
spec:
  template:
    metadata:
      name: etl-enrich-specimens-mm
      labels:
        app: etl-enrich-specimens-mm
    spec:
      restartPolicy: Never
      containers:
      - name: etl-enrich-specimens-mm
        image: atzedevries/docker-nba-etl:V2.7-13-ge6a9367a0
        env:
        - name: "ES_DNS"
          value: "elasticsearch"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "AUTO_IMPORT"
          value: "TRUE"
        - name: "ENABLE_FILEBEAT"
          value: "FALSE"
        - name: "DEFAULT_SHARDS"
          value: "24"
        - name: "NUM_REPLICAS"
          value: "0"
        - name: "REPOS"
          value: "nba-brondata-medialib:master"
        - name: "IMPORT_COMMAND"
          value: "sed -i 's/read_batch_size=1000/read_batch_size=5000/g' add-taxonomy-to-multimedia &&  ./add-taxonomy-to-multimedia"
        imagePullPolicy: Always
        volumeMounts:
        - name: nfs-pvc
          mountPath: "/payload/software/log"
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfslog
