---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-geo
  labels:
    app: etl-geo
spec:
  template:
    metadata:
      name: etl-geo
      labels:
        app: etl-geo
    spec:
      restartPolicy: Never
      containers:
      - name: etl-geo
        image: atzedevries/docker-nba-etl:V2.9
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
        - "-c"
        - >
          git clone https://github.com/naturalis/nba-brondata-geo /payload/data/geo -b $BRONDATA_TAG
          && (cd /payload/data/geo ; ./uncompress.sh)
          && git clone https://github.com/naturalis/nba-brondata-medialib /payload/data/medialib -b $MEDIALIB_TAG
          && (cd /payload/data/medialib ; ./uncompress.sh)
          && sed -i "s/#test_genera.*/$TEST_GENERA/g" /payload/software/sh/include.sh 
          && sed -i "s/truncate=true/truncate=false/g" /payload/software/sh/include.sh
          && ./geo-import 
          && rm -fr /payload/data/geo
        env:
        - name: "LOG_LEVEL"
          value: "INFO"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "BRONDATA_TAG"
          value: "prisma-test"
        - name: "MEDIALIB_TAG"
          value: "2017-07" 
        volumeMounts:
        - name: nfs-pvc
          mountPath: /payload/software/log
        - name: etl-nba-properties
          mountPath: /payload/software/conf/nba.properties
          subPath: nba.properties
        - name: etl-log4j2-xml
          mountPath: /payload/software/conf/log4j2.xml
          subPath: log4j2.xml
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfslog
      - name: etl-nba-properties
        configMap:
          name: etl.nba.properties
      - name: etl-log4j2-xml
        configMap:
          name: etl.log4j2.xml
