---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-add-taxonomy-to-specimens
  labels:
    app: etl-add-taxonomy-to-specimens
spec:
  template:
    metadata:
      name: etl-add-taxonomy-to-specimens
      labels:
        app: etl-add-taxonomy-to-specimens
    spec:
      restartPolicy: Never
      containers:
      - name: etl-add-taxonomy-to-specimens
        image: atzedevries/docker-nba-etl:V2.7-13-ge6a9367a0
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
        - "-c"
        - > 
          sed -i 's/read_batch_size=1000/read_batch_size=500/g' add-taxonomy-to-specimens 
          && ./add-taxonomy-to-specimens
        volumeMounts:
        - name: nfs-pvc
          mountPath: "/payload/software/log"
        - name: etl-nba-properties
          mountPath: /payload/software/conf/nba.properties
          subPath: nba.properties
        - name: etl-log4j2-xml
          mountPath: /payload/software/conf/log4j2.xml
          subPath: log4j2.xml
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfslog
      - name: etl-nba-properties
        configMap:
          name: etl.nba.properties
      - name: etl-log4j2-xml
        configMap:
          name: etl.log4j2.xml
